const express = require('express');
const healthRoutes = require('./health');
const contactRoutes = require('./contact');
const pricingRoutes = require('./pricing');
const authRoutes = require('./auth');
const sitesRoutes = require('./sites');
const eventsRoutes = require('./events');
const inventoryRoutes = require('./inventory');
const animalsRoutes = require('./animals');
const tasksRoutes = require('./tasks');
const adminRoutes = require('./admin');
const postingRoutes = require('./posting');
const accountingRoutes = require('./accounting');
const purchasingRoutes = require('./purchasing');
const assetsRoutes = require('./assets');
const vehiclesRoutes = require('./vehicles');
const landTractsRoutes = require('./landTracts');
const structuresRoutes = require('./structures');
const areasRoutes = require('./areas');
const binsRoutes = require('./bins');
const webhooksRoutes = require('./webhooks');
const billingRoutes = require('./billing');
const contactsRoutes = require('./contacts');
const usageRoutes = require('./usage');

const router = express.Router();

router.use('/health', healthRoutes);
router.use('/contact', contactRoutes);
router.use('/pricing', pricingRoutes);
router.use('/auth', authRoutes);
router.use('/sites', sitesRoutes);
router.use('/events', eventsRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/animals', animalsRoutes);
router.use('/tasks', tasksRoutes);
router.use('/admin', adminRoutes);
router.use('/posting', postingRoutes);
router.use('/accounting', accountingRoutes);
router.use('/purchasing', purchasingRoutes);
router.use('/assets', assetsRoutes);
router.use('/vehicles', vehiclesRoutes);
router.use('/land-tracts', landTractsRoutes);
router.use('/structures', structuresRoutes);
router.use('/areas', areasRoutes);
router.use('/bins', binsRoutes);
router.use('/webhooks', webhooksRoutes);
router.use('/billing', billingRoutes);
router.use('/contacts', contactsRoutes);
router.use('/usage', usageRoutes);

module.exports = router;
